export const COUNTER_CHANGE = "COUNTER_CHANGE";
export const ADD_NODE_TO_ARRAY = "ADD_NODE_TO_ARRAY";
export const SAVE_NODES_TO_FILE = "SAVE_NODES_TO_FILE";
export const DELETE_NODES_FROM_ARRAY = "DELETE_NODES_FROM_ARRAY";